In [20]:
import numpy as np
my_lst1 = [1,2,3,4,]
my_lst2 = [2,3,5,6,]
my_lst3 = [4,6,7,8,]
arr = np.array([my_lst1,my_lst2,my_lst3])
type(arr)
print(arr)
arr.shape

[[1 2 3 4]
 [2 3 5 6]
 [4 6 7 8]]


(3, 4)

my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,5,6,7]
my_lst3 = [4,6,7,8,9]
arr = np.array(my_lst1,my_lst2,my_lst3)
type(arr)